### ISSUE TITLE
Javadocs for Groovy classes should be generated properly

### ISSUE THREAD

**Issue by unixoid** [krasserm/ipf#60]
IPF release process includes generation of Javadoc HTMLs.  Javadocs for Groovy classes are generated from corresponding Java stubs.  But the Groovy stub compiler does not copy Javadoc comments into generated stub files.  Therefore no Javadoc HTMLs are actually generated.

OTOH, the IPF DSL documentation plugin is somehow able to parse Groovy files and extract DSL documentation elements from there.

It would be terrific when the same technique could be applied onto all IPF Groovy classes in order to properly generate Javadoc HTMLs for them.  Some reformatting of Groovy files (e.g. inserting semicolons at line ends) may be neccessary though.

**Comment by unixoid** [comment]
Groovydoc should be used instead of standard javadoc.
Links:
http://groovy.codehaus.org/The+groovydoc+Ant+task
http://stackoverflow.com/questions/5325259/groovydoc-as-maven-plugin

**Comment by stanojevic-boris** [comment]
The groovydoc tool is not production-ready. At least not for our use-case. So instead of using groovydoc I have defined a new profile ("gapidoc") which creates the groovy stubs with older version of gmaven-plugin (1.0) which respects the javadoc annotations on stub generation. Desired outcome should be provided by running the:

mvn javadoc:aggregate -Pgapidoc

To get these javadocs inside of the ipf-project-site-reporting section run:

mvn site:site
mvn javadoc:aggregate -Pgapidoc
mvn site:deploy

Closing the issue...
