### ISSUE TITLE
Add "ipf" prefix to all ipf artifactId's

### ISSUE THREAD

**Issue by stanojevic-boris** [krasserm/ipf#74]
1. Add "ipf" prefix to all ipf artifacts to avoid collisions with other third-party artifacts
2. For artifacts having "org.openehealth.ipf.platform-camel" groupId change to "org.openehealth.ipf.camel". Additionally instead of "platform-camel" use the "ipf-camel" prefix for artifactId's

**Comment by krasserm** [comment]
Why don't you use the group id as prefix (as seen by many OSGi ready jars)?

**Comment by krasserm** [comment]
As this breaks Maven configs of _all_ IPF users, shouldn't we discuss that on the user list (or at least the dev list) before?

**Comment by stanojevic-boris** [comment]
> > Why don't you use the group id as prefix (as seen by many OSGi ready jars)?
> > Most of ipf-based applications are non-OSGi; after assembling they are ending up with the artifactId-only as a filename. After all camel has the "camel" prefix also for all their artifacts.
> > 
> > As this breaks Maven configs of all IPF users, shouldn't we discuss that on the user list (or at least the dev list) before?
> > Agree

**Comment by 4effo** [comment]
It's expensive but it makes sense to me.
+1

2011/8/2 stanojevic-boris <
reply@reply.github.com>

**Comment by krasserm** [comment]
@Boris

It doesn't matter if the IPF apps are OSGi based or not. IPF artifacts can be used within any apps. What counts is that IPF artifacts support OSGi deployments and that's why it makes senses to use such a naming scheme. An artifact naming scheme based on the contained packages would make sense because
1. this is used within many other projects as well (least surpise to our users) and
2. it avoids making exceptions (item 2 in your initial proposal) to a general rule (item 1)

**Comment by krasserm** [comment]
See also my comments at
http://groups.google.com/group/ipf-dev/msg/03a46e1572d910fc and
http://groups.google.com/group/ipf-dev/msg/7177a570942771fb

**Comment by unixoid** [comment]
Implemented in IPF 2.3-m2
